### ISSUE TITLE
Value of switch never changes.

### ISSUE THREAD

**Issue by thomaskblr** [fivdi/onoff#114]
How does one get the value of a switch upon start up? I tried button.read and button.readSync() and neither give the info needed.

**Comment by fivdi** [comment]
The `read` and `readSync` methods are the correct methods to use.

Based on the information provided it's difficult to determine what the problem is.

- What type of board is being used?
- What is the number of the GPIO being used?
- What is the number of the pin on the expansion header being used?
- Exactly how is the button connected to the GPIO? A photo that shows everything clearly would help a lot here.
- Please post a complete program that is as short as possible that can be used to reproduce the problem.

**Comment by fivdi** [comment]
@thomaskblr any news on this one?

**Comment by thomaskblr** [comment]
Yes it was mistake on my end.  The documentation could have explained things a little better.  Thank you 

On Jun 29, 2018, at 14:14, Brian Cooke <notifications@github.com> wrote:

@thomaskblr any news on this one?

**Comment by fivdi** [comment]
Thanks for the feedback. A PR to improve the documentation or an issue describing what could be improved would be more than welcome.
