### ISSUE TITLE
return binding.writebuffer issue

### ISSUE THREAD

**Issue by fatboy95** [fivdi/onoff#43]
Working onoff I am trying to use a Hall Effect Sensor position (0-off, 1-on) to control a motor. My raspberry pi is giving me the below error. Not sure what to do next.. thank for the help.

fs.js:613
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^
Error: EBUSY, resource busy or locked
    at Error (native)
    at Object.fs.writeSync (fs.js:613:20)
    at Object.fs.writeFileSync (fs.js:1108:21)
    at new Gpio (/node_modules/onoff/onoff.js:82:8)
    at Object.<anonymous> (/home/1-28-2016/door.js:3:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by fivdi** [comment]
This can happen when onoff wants to export a GPIO to userspace but can't because the GPIO is already being used by another piece of code, perhaps in the same process, perhaps in a different process, or perhaps by the kernel. This other piece of code, wherever it happens to be, won't be using the sysfs files locates at `/sys/class/gpio` to access the GPIO.

Is there another piece of code on your Raspberry Pi that is using the GPIO in question?
Or are you using a device tree overlays that is reserving the GPIO for some purpose?

Also, try the following: open a terminal window and cd to `/sys/class/gpio`. If there is no directory called `/sys/class/gpio/gpio<put-correct-gpio-number-here>`, run the following command:
```
echo  put-correct-gpio-number-here > export
```
If an error message similar to the following is printed, something has the GPIO reserved:
```
-bash: echo: write error: Device or resource busy
```

**Comment by fivdi** [comment]
@fatboy95 what's the status here?

**Comment by fatboy95** [comment]
It was an error in my code.. thanks for the help.
