### ISSUE TITLE
RPi3B+ ACT_LED

### ISSUE THREAD

**Issue by jsimmonds2** [fivdi/onoff#95]
Having no success with BCM_GPIO "pin" 29  (the Green ACT_LED) using onoff@3.0.2
(works fine from C++ using wiringPi though . . )

Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

CoffeeScript code
```
gpio = require('onoff').Gpio

act_led = new gpio 29, 'out'               # ACT_LED
```
Looks like this BCM pin is not allowed to be exported . .  (b.t.w. what does export really achieve ?)

Here's the crash

```
fs.js:735
    return binding.writeBuffer(fd, buffer, offset, length, position);
                   ^

 Error: EBUSY: resource busy or locked, write
     at Object.fs.writeSync (fs.js:735:20)
     at Object.fs.writeFileSync (fs.js:1309:24)
     at new Gpio (/home/pi/projects/JS/node_modules/onoff/onoff.js:28:10)
     at Object.<anonymous> (/home/pi/projects/JS/blink-js/play.coffee:4:11)
 [ . . . ]
```
Any help appreciated !

**Comment by fivdi** [comment]
I'm afraid this is to be expected with onoff. The GPIO that is used to control the ACT_LED is reserved by an LED driver (the leds-gpio driver if I'm not mistaken). Because it's reserved, an EBUSY error is thrown when onoff attempts to use it. I would imagine that WiringPi is avoiding this issues by writing directly to hardware registers to control the state of the LED.

> b.t.w. what does export really achieve

It tells the Linux kernel to allow a GPIO pin to be used from userspace (a "normal" user program.)
